[[UNRESOLVED_MEMBER]]
id = "CODEWARE_10901"
span_starts_with = "scrollArea.useInternalMask"
message = "Install Codeware 1.9.1 or higher"

[[UNRESOLVED_MEMBER]]
id = "CODEWARE_10901"
span_starts_with = "scrollController.ScrollArea"
message = "Install Codeware 1.9.1 or higher"
